name: stories_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter         
  intl: ^0.17.0 
  flutter_screenutil: ^5.5.3+2
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  curved_navigation_bar: ^1.0.3
  firebase_core: ^1.20.1
  firebase_storage: ^10.3.5
  cloud_firestore: ^3.4.4
  image_picker: ^0.8.5+3
  # octo_image: ^1.0.2
  flutter_widget_from_html: ^0.8.5
  flutter_svg: ^1.1.4
  url_launcher: ^6.1.5
  chewie: ^1.3.4
  video_player: ^2.4.7
  audioplayers: ^0.20.1
  auto_animated: ^3.1.0
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3+1
  path: ^1.8.1
  path_provider: ^2.0.11
  connectivity_plus: ^2.3.6+1
  dio: ^4.0.6
  percent_indicator: ^4.2.2
  file_picker: ^5.0.1
  gallery_saver: ^2.3.2
  webviewx: ^0.2.1
  lottie: ^1.4.2
  shimmer: ^2.0.0
  flutter_zoom_drawer: ^3.0.3
  google_mobile_ads: ^2.0.1
  firebase_messaging: ^13.0.1
  flutter_local_notifications: ^9.9.1
  firebase_in_app_messaging: ^0.6.0+24
  share_plus: ^4.1.0
  facebook_audience_network: ^1.0.1
  wakelock: ^0.6.2
 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  generate: true 

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Arabic Regular 400.otf
          weight: 400
        - asset: assets/font/Montserrat-Arabic Black 900.otf
          weight: 900
        - asset: assets/font/Montserrat-Arabic Bold 700.otf
          weight: 700
        - asset: assets/font/Montserrat-Arabic ExtraBold 800.otf
          weight: 800
        - asset: assets/font/Montserrat-Arabic SemiBold 600.otf
          weight: 600
        - asset: assets/font/Montserrat-Arabic Medium 500.otf
          weight: 500
        - asset: assets/font/Montserrat-Arabic Light 300.otf
          weight: 300
